# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Bruna/Trabalho3/filosofo_make

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Bruna/Trabalho3/filosofo_make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Bruna/Trabalho3/filosofo_make/CMakeFiles /home/Bruna/Trabalho3/filosofo_make/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Bruna/Trabalho3/filosofo_make/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unitTestRunner

# Build rule for target.
unitTestRunner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unitTestRunner
.PHONY : unitTestRunner

# fast build rule for target.
unitTestRunner/fast:
	$(MAKE) -f CMakeFiles/unitTestRunner.dir/build.make CMakeFiles/unitTestRunner.dir/build
.PHONY : unitTestRunner/fast

#=============================================================================
# Target rules for targets named mainApp

# Build rule for target.
mainApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mainApp
.PHONY : mainApp

# fast build rule for target.
mainApp/fast:
	$(MAKE) -f CMakeFiles/mainApp.dir/build.make CMakeFiles/mainApp.dir/build
.PHONY : mainApp/fast

#=============================================================================
# Target rules for targets named GraphoLibrary

# Build rule for target.
GraphoLibrary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GraphoLibrary
.PHONY : GraphoLibrary

# fast build rule for target.
GraphoLibrary/fast:
	$(MAKE) -f CMakeFiles/GraphoLibrary.dir/build.make CMakeFiles/GraphoLibrary.dir/build
.PHONY : GraphoLibrary/fast

grafo.o: grafo.cpp.o

.PHONY : grafo.o

# target to build an object file
grafo.cpp.o:
	$(MAKE) -f CMakeFiles/GraphoLibrary.dir/build.make CMakeFiles/GraphoLibrary.dir/grafo.cpp.o
.PHONY : grafo.cpp.o

grafo.i: grafo.cpp.i

.PHONY : grafo.i

# target to preprocess a source file
grafo.cpp.i:
	$(MAKE) -f CMakeFiles/GraphoLibrary.dir/build.make CMakeFiles/GraphoLibrary.dir/grafo.cpp.i
.PHONY : grafo.cpp.i

grafo.s: grafo.cpp.s

.PHONY : grafo.s

# target to generate assembly for a file
grafo.cpp.s:
	$(MAKE) -f CMakeFiles/GraphoLibrary.dir/build.make CMakeFiles/GraphoLibrary.dir/grafo.cpp.s
.PHONY : grafo.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mainApp.dir/build.make CMakeFiles/mainApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mainApp.dir/build.make CMakeFiles/mainApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mainApp.dir/build.make CMakeFiles/mainApp.dir/main.cpp.s
.PHONY : main.cpp.s

testRunner.o: testRunner.cpp.o

.PHONY : testRunner.o

# target to build an object file
testRunner.cpp.o:
	$(MAKE) -f CMakeFiles/unitTestRunner.dir/build.make CMakeFiles/unitTestRunner.dir/testRunner.cpp.o
.PHONY : testRunner.cpp.o

testRunner.i: testRunner.cpp.i

.PHONY : testRunner.i

# target to preprocess a source file
testRunner.cpp.i:
	$(MAKE) -f CMakeFiles/unitTestRunner.dir/build.make CMakeFiles/unitTestRunner.dir/testRunner.cpp.i
.PHONY : testRunner.cpp.i

testRunner.s: testRunner.cpp.s

.PHONY : testRunner.s

# target to generate assembly for a file
testRunner.cpp.s:
	$(MAKE) -f CMakeFiles/unitTestRunner.dir/build.make CMakeFiles/unitTestRunner.dir/testRunner.cpp.s
.PHONY : testRunner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... unitTestRunner"
	@echo "... mainApp"
	@echo "... GraphoLibrary"
	@echo "... grafo.o"
	@echo "... grafo.i"
	@echo "... grafo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testRunner.o"
	@echo "... testRunner.i"
	@echo "... testRunner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

